### PR TITLE
fix wantMethod

### PR DESCRIPTION
**Pull request by efpato**

### CODE REVIEW

**Comment by kgrandis** [comment]
Thanks for the PR. Is there a test you can add that would fail under the current build to show the need for this patch?

**Comment by alanhamlett** [comment]
FYI, without this pull request all tests are skipped in Python 3.

**Comment by kgrandis** [comment]
https://travis-ci.org/kgrandis/nose-exclude/jobs/76914057  shows all the tests running on py3.4
oddly, https://travis-ci.org/kgrandis/nose-exclude/jobs/76914058  (py3.3) also passes by travis, but is littered with AttributeErrors

**Comment by alanhamlett** [comment]
Sorry, what I meant was when running tests on a different codebase with nose-exclude enabled, if the nose PluginManager calls the `wantMethod` from nose-exclude before other plugins then tests will be skipped silently. This is because the PluginManager decides to run a test from the first non `None` return value from `wantMethod` by looping through all plugins and calling `wantMethod`.

**Comment by alanhamlett** [comment]
This is fixed with #11.

**Comment by kgrandis** [comment]
fixed by #11. Thanks @alanhamlett

**Pull request closed without merging**
